### ISSUE TITLE
Failing to install prerequisites behind a firewall

### ISSUE THREAD

**Issue by ricsiLT** [JetBrains/profiler-self-api#14]
Hi,

I'm seeing the following exception:

```
Ensuring that dotTrace prerequisite is installed...
System.AggregateException: One or more errors occurred. (Failed to download prerequisite package. Please, check the NuGet URL and Internet connection.
[https://api.nuget.org/v3/index.json])
 ---> System.Exception: Failed to download prerequisite package. Please, check the NuGet URL and Internet connection.
[https://api.nuget.org/v3/index.json]
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at JetBrains.Profiler.SelfApi.Impl.NuGet.V3.GetNupkgContentAsync(HttpClient http, Uri indexUrl, String packageId, SemanticVersion packageVersion, CancellationToken cancellationToken)
   at JetBrains.Profiler.SelfApi.Impl.PrerequisiteBase.DoDownloadAsync(Uri nugetUrl, NuGetApi nugetApi, String downloadTo, IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at JetBrains.Profiler.SelfApi.Impl.PrerequisiteBase.DoDownloadAsync(Uri nugetUrl, NuGetApi nugetApi, String downloadTo, IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at BenchmarkDotNet.Diagnostics.dotTrace.DotTraceToolBase.Init(DiagnoserActionParameters parameters)

```

when trying to run benchmark with following attributes:

```
[DotTraceDiagnoser]
[SimpleJob, InProcess]
public class SqliteDbReadBenchmark
```

I'm behind a corporate firewall and we typically specify our internal nuget feed when we need to download something this way. Is there any way to override the link you need?

**Comment by ricsiLT** [comment]
So, apparently `[DotTraceDiagnoser]` takes in parameters, and it almost should do what I need, but latest version has a bug in there. It takes in `Uri` as parameter and I can't build it inline:

```
[DotTraceDiagnoser(new Uri("https://internal.repo.com/artifactory/api/nuget/v3/"))]
public class SqliteDbReadBenchmark
```

gives out:

```
2>SqliteDbReadBenchmark.cs(12,2): Error CS0181 : Attribute constructor parameter 'nugetUrl' has type 'Uri', which is not a valid attribute parameter type
```

**Comment by gassanosh** [comment]
Probably you are talking about DotTraceDiagnoser attribute in BenchmarkDotNet? In that case and if the problem is in DotTraceDiagnoser the change must be done in BenchmarkDotNet.

Our api has EnsurePrerequisite method where you could specify URL of NuGet mirror:
```
    /// <summary>
    /// Makes sure that the dotTrace command-line profiler is downloaded and is ready to use.
    /// </summary>
    /// <remarks>
    /// 1. Looks for dotTrace executable in the same directory with the running assembly. Uses it if it's found.<br/>
    /// 2. Downloads `JetBrains.dotTrace.CommandLineTools` NuGet package into the <paramref name="downloadTo"/>
    /// directory and uses the dotTrace command-line profiler from this package. The package version is defined by <see cref="CommandLineToolsConfig.NupkgVersion"/>.
    /// The command-line profiler is saved to `{downloadTo}/dotTrace.{NupkgVersion}`
    /// If the executable file exists, a new one is not downloaded.
    /// </remarks>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <param name="progress">Download progress callback from 0.0 to 100.0. If null, progress is not reported.</param>
    /// <param name="nugetUrl">URL of NuGet mirror. If null, www.nuget.org is used.</param>
    /// <param name="nugetApi">NuGet API version.</param>
    /// <param name="downloadTo">NuGet download destination directory. If null, %LocalAppData% is used.</param>
    public static Task EnsurePrerequisiteAsync(
      CancellationToken cancellationToken,
      IProgress<double> progress = null,
      Uri nugetUrl = null,
      NuGetApi nugetApi = NuGetApi.V3,
      string downloadTo = null)
```

**Comment by ricsiLT** [comment]
Exactly! Sorry for posting here first :D I was following JetBrains guide for this benchmarking so I assumed this is the project I have to raise an issue with but later dug deeper and understood that I booked it against wrong repo :( Should I close the issue?

**Comment by gassanosh** [comment]
Not problem at all, I closed the issue.
